# Generated by Django 4.2.1 on 2023-07-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='inventory',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
