# Generated by Django 4.2.1 on 2023-05-09 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0002_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
