# Generated by Django 4.2.1 on 2023-07-07 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0005_alter_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
