# Generated by Django 4.2.1 on 2023-07-07 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0009_completedorderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='inventory',
        ),
    ]
