# Generated by Django 4.2.1 on 2023-05-15 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0009_alter_shippinginfo_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippinginfo',
            name='email',
        ),
    ]
