# Generated by Django 4.2.1 on 2023-07-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0010_remove_products_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='inventory',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
