# Generated by Django 4.2.1 on 2023-05-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0010_remove_shippinginfo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ShippingInfo',
        ),
    ]
