# Generated by Django 4.2.1 on 2023-07-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0011_products_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='address',
            field=models.CharField(default='address', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='phone_number',
            field=models.CharField(default='phone_number', max_length=20),
            preserve_default=False,
        ),
    ]
