# Generated by Django 4.2.1 on 2023-07-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0017_alter_products_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
