# Generated by Django 4.2.1 on 2023-05-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0012_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='detail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='sale_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
